package project;
// Generated by Selenium IDE

import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

import dataDriven.ReadFromFile;
import dataDriven.User;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.AssertJUnit;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.testng.Assert.assertEquals;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.awt.Robot;
import java.net.MalformedURLException;
import java.net.URL;

public class TestSignUp {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@DataProvider (name = "users_data_driven")
	public Object[] dpMethod() {
		ReadFromFile fileProducts = new ReadFromFile();
		return fileProducts.getUsers();
	}
	
	@BeforeMethod
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\dvir tayeb\\Documents\\Selnium\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@AfterMethod
	public void tearDown() {
    driver.quit();
	}

	@Test (dataProvider = "users_data_driven")
	public void test_signUp(User user) throws InterruptedException {
		// Test name: test_sign_up
		// Step # | name | target | value
		System.out.println("Data inserted Sign Up: username="+user.getUsername()+", password="+ user.getPassword());
		driver.get("https://www.demoblaze.com/index.html");
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		WebElement signUp = driver.findElement(By.id("signin2"));
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		signUp.click();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		WebElement username = driver.findElement(By.id("sign-username"));
		username.sendKeys(user.getUsername());
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		WebElement password = driver.findElement(By.id("sign-password"));
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
		Thread.sleep(1000);
		password.sendKeys(user.getPassword());
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		WebElement signUpEnd = driver.findElement(By.xpath("//*[@id=\"signInModal\"]/div/div/div[3]/button[2]"));
		signUpEnd.click();
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
		Thread.sleep(2000);
		Alert alert = driver.switchTo().alert();
		String alert_signUp = driver.switchTo().alert().getText();
//		assertEquals(alert_signUp, "This user already exist.", alert_signUp);
		assertEquals(alert_signUp, "Sign up successful.", alert_signUp);
		alert.accept();
		
		driver.switchTo().defaultContent();
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
	}
}
